import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    padding: 24,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    flexGrow: 1,
    padding: 24,
    backgroundColor: "#fff",
  },
  logo: {
    fontSize: 64,
    marginBottom: 12,
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
    color: "#111827",
  },
  subtitle: {
    fontSize: 16,
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 24,
  },
  text: {
    marginTop: 8,
    fontSize: 16,
    textAlign: "center",
  },
  centerContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  smallCard: {
    width: "100%",
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#f4f4f5",
    marginBottom: 20,
  },
  smallCardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 6,
  },
  smallText: {
    fontSize: 14,
    color: "#6b7280",
    lineHeight: 20,
  },
  label: {
    fontSize: 14,
    color: "#666",
    marginTop: 12,
  },
  value: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 4,
    color: "#111827",
  },
  cardLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#854d0e",
  },
  heroCard: {
    width: "100%",
    padding: 24,
    borderRadius: 24,
    backgroundColor: "#fef3c7",
    marginBottom: 20,
  },
  heroValue: {
    fontSize: 44,
    fontWeight: "bold",
    marginTop: 8,
    color: "#111827",
  },
  resultCard: {
    width: "100%",
    padding: 20,
    borderRadius: 18,
    backgroundColor: "#f9fafb",
    marginBottom: 16,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 4,
  },
  error: {
    color: "red",
    fontSize: 15,
    textAlign: "center",
    marginBottom: 16,
    marginTop: 8,
  },
  cameraContainer: {
    width: "100%",
    height: 460,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#000",
  },
  camera: {
    flex: 1,
  },
  captureButton: {
    padding: 16,
    backgroundColor: "#facc15",
    alignItems: "center",
  },
  captureButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111827",
  },
  previewContainer: {
    width: "100%",
    alignItems: "center",
  },
  previewImage: {
    width: "100%",
    height: 460,
    borderRadius: 24,
    resizeMode: "cover",
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
  },
  primaryButton: {
    backgroundColor: "#facc15",
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 16,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "bold",
  },
  secondaryButton: {
    backgroundColor: "#e5e7eb",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "bold",
  },
  resetButton: {
    backgroundColor: "#fee2e2",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    marginTop: 8,
    marginBottom: 32,
  },
  resetButtonText: {
    color: "#991b1b",
    fontSize: 16,
    fontWeight: "bold",
  },
  loadingBox: {
    alignItems: "center",
    marginTop: 20,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    color: "#111827",
    backgroundColor: "#fff",
    marginTop: 6,
    },
  helperText: {
    fontSize: 13,
    color: "#6b7280",
    lineHeight: 20,
    marginTop: 14,
    },
  primaryButtonFull: {
    backgroundColor: "#facc15",
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 16,
    alignItems: "center",
    width: "100%",
    marginTop: 8,
    marginBottom: 32,
    },
});