import { StyleSheet } from 'react-native';

import { APP_BACKGROUND_COLOR, MAIN_TEXT_COLOR } from '@/src/constants/colors';
import {
  FONT_INTER_BLACK,
  FONT_INTER_BOLD,
  FONT_INTER_EXTRABOLD,
  FONT_INTER_REGULAR,
  FONT_INTER_SEMIBOLD,
} from '@/src/constants/fonts';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: APP_BACKGROUND_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
    backgroundColor: APP_BACKGROUND_COLOR,
  },
  logo: {
    fontSize: 64,
    marginBottom: 12,
  },
  title: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 30,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
    color: MAIN_TEXT_COLOR,
  },
  subtitle: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 16,
    color: MAIN_TEXT_COLOR,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 24,
  },
  text: {
    fontFamily: FONT_INTER_REGULAR,
    marginTop: 8,
    fontSize: 16,
    textAlign: 'center',
    color: MAIN_TEXT_COLOR,
  },
  centerContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallCard: {
    width: '100%',
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#f4f4f5',
    marginBottom: 20,
  },
  smallCardTitle: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
    color: MAIN_TEXT_COLOR,
  },
  smallText: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 14,
    color: MAIN_TEXT_COLOR,
    lineHeight: 20,
  },
  label: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 14,
    color: MAIN_TEXT_COLOR,
    marginTop: 12,
  },
  value: {
    fontFamily: FONT_INTER_SEMIBOLD,
    fontSize: 18,
    fontWeight: '600',
    marginTop: 4,
    color: MAIN_TEXT_COLOR,
  },
  cardLabel: {
    fontFamily: FONT_INTER_SEMIBOLD,
    fontSize: 15,
    fontWeight: '600',
    color: MAIN_TEXT_COLOR,
  },
  heroCard: {
    width: '100%',
    padding: 24,
    borderRadius: 24,
    backgroundColor: '#fef3c7',
    marginBottom: 20,
  },
  heroValue: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 44,
    fontWeight: 'bold',
    marginTop: 8,
    color: MAIN_TEXT_COLOR,
  },
  resultCard: {
    width: '100%',
    padding: 20,
    borderRadius: 18,
    backgroundColor: '#f9fafb',
    marginBottom: 16,
  },
  resultTitle: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 18,
    fontWeight: 'bold',
    color: MAIN_TEXT_COLOR,
    marginBottom: 4,
  },
  error: {
    fontFamily: FONT_INTER_REGULAR,
    color: MAIN_TEXT_COLOR,
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  cameraContainer: {
    width: '100%',
    height: 460,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
  },
  captureButton: {
    padding: 16,
    backgroundColor: '#facc15',
    alignItems: 'center',
  },
  captureButtonText: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#111827',
  },
  previewContainer: {
    width: '100%',
    alignItems: 'center',
  },
  previewImage: {
    width: '100%',
    height: 460,
    borderRadius: 24,
    resizeMode: 'cover',
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  primaryButton: {
    backgroundColor: '#facc15',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 16,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontFamily: FONT_INTER_BOLD,
    color: '#111827',
    fontSize: 16,
    fontWeight: 'bold',
  },
  secondaryButton: {
    backgroundColor: '#e5e7eb',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontFamily: FONT_INTER_BOLD,
    color: '#111827',
    fontSize: 16,
    fontWeight: 'bold',
  },
  resetButton: {
    backgroundColor: '#fee2e2',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 32,
  },
  resetButtonText: {
    fontFamily: FONT_INTER_BOLD,
    color: '#991b1b',
    fontSize: 16,
    fontWeight: 'bold',
  },
  loadingBox: {
    alignItems: 'center',
    marginTop: 20,
  },
  input: {
    fontFamily: FONT_INTER_REGULAR,
    width: '100%',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    color: MAIN_TEXT_COLOR,
    backgroundColor: '#fff',
    marginTop: 6,
  },
  helperText: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 13,
    color: MAIN_TEXT_COLOR,
    lineHeight: 20,
    marginTop: 14,
  },
  primaryButtonFull: {
    backgroundColor: '#facc15',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 16,
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
    marginBottom: 32,
  },
  progressHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressText: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 13,
    fontWeight: '700',
    color: MAIN_TEXT_COLOR,
  },
  progressTrack: {
    width: '100%',
    height: 14,
    borderRadius: 999,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
    marginBottom: 32,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#22c55e',
  },
  questionCard: {
    width: '100%',
    padding: 24,
    borderRadius: 24,
    backgroundColor: '#fef3c7',
    marginBottom: 24,
  },
  questionTitle: {
    fontFamily: FONT_INTER_EXTRABOLD,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    color: MAIN_TEXT_COLOR,
    textAlign: 'center',
  },
  questionSubtitle: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 16,
    lineHeight: 24,
    color: MAIN_TEXT_COLOR,
    textAlign: 'center',
    marginTop: 12,
  },
  optionList: {
    width: '100%',
    gap: 14,
    marginBottom: 24,
  },
  optionButton: {
    width: '100%',
    padding: 20,
    borderRadius: 18,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  optionLabel: {
    fontFamily: FONT_INTER_EXTRABOLD,
    fontSize: 20,
    fontWeight: '800',
    color: MAIN_TEXT_COLOR,
  },
  optionDescription: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 14,
    color: MAIN_TEXT_COLOR,
    marginTop: 4,
  },
  secondaryButtonFull: {
    backgroundColor: '#e5e7eb',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    width: '100%',
    marginBottom: 32,
  },
  mainContainer: {
    flexGrow: 1,
    padding: 20,
    paddingBottom: 40,
    backgroundColor: APP_BACKGROUND_COLOR,
  },
  greetingSection: {
    marginBottom: 12,
  },
  homeLogoRow: {
    marginBottom: 24,
    alignItems: 'flex-start',
  },
  greetingTitle: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
  },
  greetingSubtitle: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 15,
    lineHeight: 22,
    color: MAIN_TEXT_COLOR,
    marginTop: 2,
  },
  circularProgressWrapper: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circularProgressTextWrapper: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreCard: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#d2c5ac',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  scoreValue: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 26,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
  },
  scoreMax: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 12,
    fontWeight: '700',
    color: MAIN_TEXT_COLOR,
  },
  scoreContent: {
    flex: 1,
  },
  scoreBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#8efc6e',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    marginBottom: 8,
  },
  scoreBadgeText: {
    fontFamily: FONT_INTER_EXTRABOLD,
    fontSize: 12,
    fontWeight: '800',
    color: MAIN_TEXT_COLOR,
  },
  scoreDescription: {
    fontFamily: FONT_INTER_REGULAR,
    fontSize: 13,
    lineHeight: 19,
    color: MAIN_TEXT_COLOR,
  },
  estimateGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  estimateMiniCard: {
    width: '48%',
    minHeight: 110,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#d2c5ac',
    borderRadius: 18,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  estimateIcon: {
    fontSize: 24,
    marginBottom: 6,
  },
  estimateLabel: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 12,
    fontWeight: '700',
    color: MAIN_TEXT_COLOR,
    textAlign: 'center',
    marginBottom: 4,
  },
  estimateValue: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 18,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
    textAlign: 'center',
  },
  estimateSmallValue: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
    textAlign: 'center',
  },

  bottomTabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 16,
    backgroundColor: APP_BACKGROUND_COLOR,
    borderTopWidth: 2,
    borderColor: '#d2c5ac',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  bottomTabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 18,
  },
  bottomTabActive: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 20,
    backgroundColor: '#ffc928',
    borderRadius: 999,
    borderBottomWidth: 4,
    borderBottomColor: '#765a00',
    transform: [{ translateY: -4 }],
  },
  bottomTabIcon: {
    fontSize: 22,
  },
  bottomTabActiveIcon: {
    fontSize: 22,
  },
  bottomTabText: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 12,
    fontWeight: '700',
    color: MAIN_TEXT_COLOR,
    marginTop: 2,
  },
  bottomTabActiveText: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 12,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
    marginTop: 2,
  },
  providerList: {
    gap: 16,
  },
  providerCard: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#d2c5ac',
    borderRadius: 18,
    padding: 16,
    gap: 14,
  },
  providerHeaderRow: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'flex-start',
  },
  providerLogo: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: '#ebe1d1',
    borderWidth: 1,
    borderColor: '#d2c5ac',
    alignItems: 'center',
    justifyContent: 'center',
  },
  providerLogoText: {
    fontSize: 30,
  },
  providerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  providerName: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 22,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
  },
  providerLocation: {
    fontFamily: FONT_INTER_REGULAR,
    color: MAIN_TEXT_COLOR,
    fontSize: 13,
    marginTop: 4,
  },
  providerRating: {
    fontFamily: FONT_INTER_EXTRABOLD,
    color: MAIN_TEXT_COLOR,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 4,
  },
  providerReviews: {
    fontFamily: FONT_INTER_BOLD,
    color: MAIN_TEXT_COLOR,
    fontWeight: '700',
  },
  viewProfileButton: {
    flex: 1,
    backgroundColor: '#765a00',
    paddingVertical: 13,
    borderRadius: 14,
    alignItems: 'center',
  },
  viewProfileButtonText: {
    fontFamily: FONT_INTER_BLACK,
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  profileLinkText: {
    fontFamily: FONT_INTER_BOLD,
    fontSize: 14,
    lineHeight: 20,
    color: MAIN_TEXT_COLOR,
    fontWeight: '700',
    marginTop: 4,
  },
  providerSecondaryButton: {
    flex: 1,
    backgroundColor: '#1f7108',
    paddingVertical: 13,
    borderRadius: 14,
    alignItems: 'center',
  },
  providerSecondaryButtonText: {
    fontFamily: FONT_INTER_BLACK,
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  viewProfileButtonFull: {
    width: '100%',
    backgroundColor: '#765a00',
    paddingVertical: 13,
    borderRadius: 14,
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'flex-end',
  },
  providerModalCard: {
    width: '100%',
    backgroundColor: APP_BACKGROUND_COLOR,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 20,
    borderWidth: 2,
    borderColor: '#d2c5ac',
  },
  providerModalHeader: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
    marginBottom: 18,
  },
  providerLogoLarge: {
    width: 70,
    height: 70,
    borderRadius: 18,
    backgroundColor: '#ebe1d1',
    borderWidth: 1,
    borderColor: '#d2c5ac',
    alignItems: 'center',
    justifyContent: 'center',
  },
  providerLogoTextLarge: {
    fontSize: 36,
  },
  providerModalTitle: {
    fontFamily: FONT_INTER_BLACK,
    fontSize: 26,
    fontWeight: '900',
    color: MAIN_TEXT_COLOR,
  },
  providerModalSection: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#d2c5ac',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
  },
  providerModalActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  modalCloseButton: {
    width: '100%',
    backgroundColor: '#fb3f00',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    fontFamily: FONT_INTER_BLACK,
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
});
